### ISSUE TITLE
ErrCode=-9

### ISSUE THREAD

**Issue by shimmervoid** [enerc/VulkanXMRMiner#1]
Hello,

Thanks for providing this miner. Upon starting, I get the following error after "Monitoring listen port" prompt

`Failure in vkCreateInstance at 69 /home/cr-3/VulkanXMRMiner/src/mvulkan.cpp  ErrCode=-9`

Ubuntu 18.04 | Linux 4.20.6-042006-generic | ROCm 2.1 | Vega FE

**Comment by enerc** [comment]
Hello, and sorry for the delay.
I am running on Rocm 2.1 with Vega, so it should work.
Please check the json file in  /etc/vulkan/icd.d/ as explained in the drivers installation section.

This is how it works:
- rocm provides gpu drivers,
- the miner looks for libvulkan (version 1.1.77 and 1.1.97 have been tested ok - I installed them with apt-get install libvulkan1)
- the miner then opens /etc/vulkan/icd.d/* and look for api version and library_path. This configuration file comes from amdgpu-pro installation.
- the library_path should reference a library that process the SPIR-V code, translate it to assembly and then call rocm the execute the programs.

I had this -9 error once, where the version api was 1.0.xx not 1.1.xxx in /etc/vulkan/icd.d/*

As for for amdgpu-pro I checked 18.40, 18.50. 17.60 works with RX550/560/R9 but probably not with Vega. 

The way I now install amdgpu-pro on rocm it is to extract the deb package, and then just link the amdvlk64.so file in the icd configuration file. You just need the config file and the so file to make it work.

**Comment by shimmervoid** [comment]
Miner works like a charm now. Have some tweaking to do. Thanks so much for your help!

``[11:46:15] 51326.4H/s 17/0/0 [0]:13783.5H/s 5/0  [1]:12507.8H/s 6/0  [2]:12508.7H/s 1/0  [3]:12526.4H/s 5/0``
