### ISSUE TITLE
Instant crash

### ISSUE THREAD

**Issue by Asphxiated** [enerc/VulkanXMRMiner#13]
I was having the problem of "waiting for blob..." continually as described in a solved issue ticket, now after downloading the updated binary I can see that it connects to my mining server, I usually use minexmr.com but I tried multiple just to see I it had something to do with my mining site and it doesn't seem to matter. 

It's hard for me to get screenshot, but if you really need one I will try to get one, but it basically says "...connecting to xxxx server...... DONE"

and then it exits. 

I have my AMD drivers set to compute, does this matter? Anyone got any ideas?

thanks!

**Comment by enerc** [comment]
Which algo are you mining ?

**Comment by Asphxiated** [comment]
well monero, specifically the new CN4 algo that came out in around March 9th I'm not sure why you didn't know this because it is an xmr miner that I am reporting this problem to. Thanks for the reply though man.

**Comment by enerc** [comment]
Could you enable  "debug_network" : "true" in config.json and report the RECV line after the login? Sure the new algo works. The blob should start with 09..... If on Windows, use the latest build. Thanks.
