### ISSUE TITLE
Disable one GPU?

### ISSUE THREAD

**Issue by kwejk** [enerc/VulkanXMRMiner#14]
Checking your cards
Index:0 MemorySize:1811 Gb - Intel(R) HD Graphics 610
Index:1 MemorySize:7920 Gb - Radeon RX Vega
Index:2 MemorySize:7920 Gb - Radeon RX Vega
Index:3 MemorySize:7920 Gb - Radeon RX Vega
Index:4 MemorySize:7920 Gb - Radeon RX Vega
Index:5 MemorySize:7920 Gb - Radeon RX Vega

Finding best configuration....
1048576 GPU bytes requested.
Cannot allocated GPU memory type for GPU index 0

Can i in any way ignore GPU index 0?

**Comment by enerc** [comment]
I see. I will make a fix for this error to be non blocking during initial setup.

**Comment by enerc** [comment]
Hello,
This issue should be fixed in the master.
When a card is not working under Vulkan (typically the motherboard chipset), the config tool will now return default values (cu=1,factor=8). 
When asked to use this card, say 'N' during the next step of the setup.
