### ISSUE TITLE
Support K12 algorithm for MoX coin

### ISSUE THREAD

**Issue by backupacctuname** [enerc/VulkanXMRMiner#17]
We are currently in the process of switching our PoW to K12. We would like to have official support from Vulkan miner

The only difference is the major version, it's going to be 10 for us

The modification required would probably something in this style
```c++
if (major_version == 10 && cryptoType[current_index] == MoxCrypto) {
	return K12_ALGO;		// K12
}
```

Thanks in advance

**Comment by enerc** [comment]
Looks fixed in https://github.com/mox-project/VulkanMOXMiner
