### ISSUE TITLE
ErrCode=-2

### ISSUE THREAD

**Issue by shimmervoid** [enerc/VulkanXMRMiner#4]
enerc,

I have several rigs and one seems to be really special. I've done several installs even as far as a fresh OS to no avail.

I always end up with the following on this particular rig:
`Failure in vkAllocateMemory at 191 /home/cr-2/Miners/VulkanXMRMiner/src/mvulkan.cpp  ErrCode=-2`

Perhaps you can shed some light?

Thanks!

**Comment by enerc** [comment]
Error -2 is VK_ERROR_OUT_OF_DEVICE_MEMORY. I would try to reduce the number of threads.
How much memory does vulkaninfo reports?

**Comment by shimmervoid** [comment]
It doesn't get past setup sadly, after prompting for config details it stalls instantly as follows:

```
No config.json file found, entering configuration setup...
Select a crypto:
 0 for Monero
 1 for Wownero
 2 for Aeon,Bittorium - cryptonight light
 3 for TurtleCoin
Your crypto: 3
 _____           _   _         ____      _
|_   _|   _ _ __| |_| | ___   / ___|___ (_)_ __
  | || | | | '__| __| |/ _ \ | |   / _ \| | '_ \
  | || |_| | |  | |_| |  __/ | |__| (_) | | | | |
  |_| \__,_|_|   \__|_|\___|  \____\___/|_|_| |_|

Mining pool address (hostname/IP): trtl.pool.mine2gether.com
Mining pool port: 4445
Your address (with optional .something at the end): xxxxxxxxx
Password (or x if none): x
Monitoring listen port (0 if no JSON/graphic console): 0

Checking your cards
Index:0 MemorySize:16368 Gb - Radeon Vega Frontier Edition
Index:1 MemorySize:16368 Gb - Radeon Vega Frontier Edition
Index:2 MemorySize:16368 Gb - Radeon Vega Frontier Edition
Index:3 MemorySize:16368 Gb - Radeon Vega Frontier Edition

Finding best configuration....
Failure in vkAllocateMemory at 191 /home/cr-2/Miners/VulkanXMRMiner/src/mvulkan.cpp  ErrCode=-2
```

It doesn't prompt for factor/CU/Worksize. I copied config.json from another rig and it's the same result.

**Comment by enerc** [comment]
The weird thing is during setup I just allocate 1Mb of buffer to measure the speed. So it's failing even with a very small block of memory. 
Something is definitely wrong. I would try this:
- run vulkaninfo and the cube app demo to see if they work (the cube will only work is X started)
- sudo dmesg to see if there are kernel errors reported
- check if drm error running dmesg (could be wrong BIOS settings and drm cannot allocated video memory - thinks like the 4Gb aperture in the BIOS)
- skipping index 0 in the config file (could be a defective card)

**Comment by shimmervoid** [comment]
> check if drm error running dmesg (could be wrong BIOS settings and drm cannot allocated video memory - thinks like the 4Gb aperture in the BIOS)

Disabling Above 4G decoding in BIOS fixed this issue. Thanks for the stellar support!
