### ISSUE TITLE
Windows Build Error

### ISSUE THREAD

**Issue by G-Kumaran** [enerc/VulkanXMRMiner#7]
The CMakeFiles/miner.dir is empty, but build succeeds. Any tips guys?

gk@PC MINGW64 /d/Miner/VM/VulkanXMRMiner/build
$ cmake -DWIN32=1 .. -G "MinGW Makefiles"
```-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: C:/msys64/mingw64/bin/gcc.exe
-- Check for working C compiler: C:/msys64/mingw64/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/msys64/mingw64/bin/g++.exe
-- Check for working CXX compiler: C:/msys64/mingw64/bin/g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: D:/Miner/VM/VulkanXMRMiner/build
```
gk@PC MINGW64 /d/Miner/VM/VulkanXMRMiner/build
$ mingw32-make
```Scanning dependencies of target miner
[ 10%] Building CXX object CMakeFiles/miner.dir/src/config.cpp.obj
process_begin: CreateProcess(NULL, x86_64-w64-mingw32-g++-win32 @CMakeFiles/miner.dir/includes_CXX.rsp -O1 -mavx -march=native -std=c++11 -o CMakeFiles\miner.dir\src\config.cpp.obj -c D:\Miner\VM\VulkanXMRMiner\src\config.cpp, ...) failed.
make (e=2): The system cannot find the file specified.
mingw32-make[2]: *** [CMakeFiles\miner.dir\build.make:63: CMakeFiles/miner.dir/src/config.cpp.obj] Error 2
mingw32-make[1]: *** [CMakeFiles\Makefile2:72: CMakeFiles/miner.dir/all] Error 2
mingw32-make: *** [Makefile:83: all] Error 2
```

**Comment by enerc** [comment]
Thanks for reporting. I tried cross compiling on Linux with mingw, but never on Windows. I will have a look and  fix it when I am back.
Just to be sure: x86_64-w64-mingw32-g++-win32 is in Windows path?

**Comment by G-Kumaran** [comment]
Yeah, path variables are fine

**Comment by KillerInk** [comment]
i think it has something todo with pthread and the unistd.h.
also i noted that cmake create wrong vulkan paths. Lib point to Bin/Lib and Include to Bin/Include

**Comment by enerc** [comment]
@KillerInk In 0.3 I dropped pthreads for Windows and used native win32.
Is the issue: https://github.com/msys2/MINGW-packages/issues/151 helping ?
Try to rename mingw32-make.exe to make.exe

**Comment by KillerInk** [comment]
No ;) only thing that happen, cmake no longer accept mingw^^
I started to make the code compatible with msvc. Binary get builded, but have problems with some apis.
configure pool works sofar. its now crashing when it try to create the VulkanInfo. 
But not sure if it was caused by one of my gpus not responding. i gave up yesterday and went to bed.

**Comment by enerc** [comment]
I use eclipse CDT to build the Windows binaries. Set mingw compiler, create a C++ native build project, import the src folder and build.

**Comment by KillerInk** [comment]
hm good old eclipse. im not done yet with msvc^^
<del>but my current problem is cause by vulkan.
vector subscript out of range at line
somehow it gets not filled.
https://github.com/enerc/VulkanXMRMiner/blob/master/src/mvulkan.cpp#L64
</del>

final found the problem....
_ITERATOR_DEBUG_LEVEL=0 fix the problem with msvc.

**Comment by KillerInk** [comment]
```
Checking your cards
Index:0 MemorySize:14073748835532 Gb - GeForce GTX 1660 Ti
Index:1 MemorySize:14073748835532 Gb - GeForce GTX 1050 Ti
Index:2 MemorySize:14073748835532 Gb - GeForce GTX 1660 Ti
Index:3 MemorySize:14073748835532 Gb - GeForce GTX 1660 Ti
Index:4 MemorySize:14073748835532 Gb - GeForce GTX 1660 Ti

Finding best configuration....
Card:0  4 Compute Units/Stream Multiprocessors, using factor -107374224 (-429496896 threads), local size 16
Use this card [Y/n]?:
```

is that normal?^^

**Comment by enerc** [comment]
Good findings!. Thanks. For the iterators, I think I can pass null instead of the empty array since we don't use Layers and Extensions yet.
I'am impressed by the amount of RAM you have in your cards. 14 exabytes is a lot! ^^.
Check what vulkaninfo reports, and upgrade the drivers. There is little hope this miner will work if vulkaninfo reports wrong values.

**Comment by KillerInk** [comment]
the gtx1660ti gets ignored with unsupported gpu.
only the gtx1050ti get accepted.
Using XMR Variant: cn/r
Mining started.... (Press q to stop)
[Time] 'Total H/s' 'Good shares'/'Invalid shares'/'Expired shares' [GPU] H/s 'good hashes'/'bad hashes'
[18:15:23] 61.9H/s 0/0/0 [0]:61.9H/s 0/0

cu 1 factor 1 set on gtx1050 for testing
msvc building works 👍

**Comment by enerc** [comment]
Ha Turing GPU. Vulkan Beta Driver Release Notes at https://developer.nvidia.com/vulkan-driver says it has beta support for it. Edit: You should get at least 10x more hashrate with a 1050ti.

**Comment by KillerInk** [comment]
oh wow thx.
updated driver.
```

Checking your cards
Index:0 MemorySize:8388608 Gb - GeForce GTX 1660 Ti
Index:1 MemorySize:8388608 Gb - GeForce GTX 1660 Ti
Index:2 MemorySize:8388608 Gb - GeForce GTX 1660 Ti
Index:3 MemorySize:8388608 Gb - GeForce GTX 1660 Ti
Index:4 MemorySize:8388608 Gb - GeForce GTX 1050 Ti

Finding best configuration....
Card:0  12 Compute Units/Stream Multiprocessors, using factor 0 (0 threads), local size 16
```
from a 1660 1x1x16
```
Mining started.... (Press q to stop)
[Time] 'Total H/s' 'Good shares'/'Invalid shares'/'Expired shares' [GPU] H/s 'good hashes'/'bad hashes'
[19:30:59] 6182844867018752.0H/s 0/0/0 [0]:6182844703809995.0H/s 0/0
```

its a pitty, its crashing silent

**Comment by KillerInk** [comment]
there seems something wrong with the memory calculations.

```
uint64_t getMemorySize(int index) {
	VkPhysicalDeviceMemoryProperties properties;
	vkGetPhysicalDeviceMemoryProperties(physicalDevices[index], &properties);
	for (uint32_t k = 0; k < properties.memoryTypeCount; k++) {
		VkMemoryType t = properties.memoryTypes[k];
		VkMemoryHeap h = properties.memoryHeaps[k];
		if ((t.propertyFlags&VK_MEMORY_HEAP_DEVICE_LOCAL_BIT)!=0)
			return h.size / 1024 / 1024;
	}
	return 0;
}
```
gtx1050:
```
memoryHeapCount       = 2
	memoryHeaps[0] :
		size          = 4216315904 (0xfb4fe000) (3.93 GiB)
		flags:
			VK_MEMORY_HEAP_DEVICE_LOCAL_BIT
	memoryHeaps[1] :
		size          = 4268118016 (0x1fe665000) (3.97 GiB)
		flags:
			None
```
gtx1660

```
memoryHeapCount       = 2
	memoryHeaps[0] :
		size          = 1991827456 (0x176b8e000) (1.86 GiB)
		flags:
			VK_MEMORY_HEAP_DEVICE_LOCAL_BIT
	memoryHeaps[1] :
		size          = 4268118016 (0x1fe665000) (3.97 GiB)
		flags:
			None
```

**Comment by G-Kumaran** [comment]
Vega 64s also arent happy on the cn/r on windows. Crashed at max of 15 min, or a error -4. Tried various diff config to no avail.

Interestingly cn/turtle works fine. But the performance is no were close to the SRB miners on that algo.

Would be great to see opencl being replaced by vulkan goin forth 😎

**Comment by KillerInk** [comment]
after playing around with the memory stuff i found a solution wich works on my gtx1660.

https://github.com/enerc/VulkanXMRMiner/blob/master/src/mvulkan.cpp#L102-L103

```
if ((t.propertyFlags&VK_MEMORY_HEAP_DEVICE_LOCAL_BIT)!=0)
			return h.size / h.flags / 1024 / 1024;
```

VkMemoryType heapIndex 0 PropertyFlags 1
VkMemoryHeap flags 3435973836 size 14757395258967641292
14757395258967641292 is a bit to much. but / 3435973836 = 4294967297 

wich is close to:
```
VkPhysicalDeviceMaintenance3Properties:
=======================================
maxPerSetDescriptors    = 4294967295
maxMemoryAllocationSize = 4292870144
```
i dont know how that values look for amd.

one 1660 runs now for 45min with 300h/s @ 24*12

btw nice work @enerc

**Comment by enerc** [comment]
@KillerInk  Thanks a lot for your findings!. How far can you go with the 1660? (I am getting 360 h/s with an RX550 which is a turtle compared to an 1660.)
@G-Kumaran It's the Windows TDR (Timeout Detection and Recovery). In the dist build, there is a registry file that will disable TDR. After applying the registry changes, you need to reboot to get it applied. (the -4 error aka Device Lost is when a kernel takes more than 2 seconds to be processed. It never happens on Turtle and CN Lite, but it does occur on cn/r).
@G-Kumaran Are you in the 12-13 kh/s on turtle?

**Comment by G-Kumaran** [comment]
Thx dude 😄 

As for cn/turtle:
SRBMiner - 17kh @ 200 watt
VulkanMiner - 14kh @ 215 watt (at same OC, stopped pushing the factor higher due to diminishing hash/watt performance)

**Comment by KillerInk** [comment]
at current state they dont pass 360H/s. on cuda 600-800 H/s depening on oc.
miner use to less memory ~1 gb. cuda base miner use 4-5gb.

Just realized it. Its not sending shares to the pool. On first connect the worker gets visible, but then it timeout due missing shares.

**Comment by enerc** [comment]
@KillerInk Try to use more memory and more threads. 
If the connection is closed the miner will try to reconnect every 20 seconds and print it on the console. If doubts, enable the network debugging on config.json to see what's happening.

**Comment by KillerInk** [comment]
yeah i tried.
but with 24x12 i get  350h/s
with 24x48 40.9h/s
32x48 0.0h/s freez the rig after few seconds

```
RECV {"jsonrpc":"2.0","method":"job","params":{"blob":"0b0b.......8","job_id":"2Iaz.....","target":"b64....","id":".....d7","height":....65}}
results: 0
mapMiningResults
results: 0
mapMiningResults
results: 0
mapMiningResults
results: 0
mapMiningResults
results: 0

[15:16:37] 1262.3H/s 0/0/0 [0]:316.0H/s 0/0  [1]:318.9H/s 0/0  [2]:315.3H/s 0/0  [3]:312.0H/s 0/0
.....
results: 0
RECV {"jsonrpc":"2.0","method":"job","params":{"blob":"0b0....","job_id":"eMo.....","target":"711...","id":"....","height":...65}}
results: 0
mapMiningResults
results: 0
mapMiningResults
results: 0
mapMiningResults
results: 0
mapMiningResults
results: 0
results: 0
.....
results: 0
[15:17:07] 1261.8H/s 0/0/0 [0]:315.5H/s 0/0  [1]:319.4H/s 0/0  [2]:314.7H/s 0/0  [3]:312.2H/s 0/0
results: 0
...

results: 0
[15:18:07] 1253.8H/s 0/0/0 [0]:312.8H/s 0/0  [1]:318.1H/s 0/0  [2]:312.6H/s 0/0  [3]:310.3H/s 0/0
results: 0

```
get jobs from pool but results stick 0.

**Comment by enerc** [comment]
I will add the worksize=32 option to match Nvidia warp size. That may help.
For the GTX 1660, I read that it has 22 activated SM over 24 in the silicon. Looks like 1408 cuda core are activated. So 11x8x16 should be efficient.
For the results, unless you have high difficulty from the pool you should get results. In doubt hardcode difficulty (say 5000) in network.cpp:429.

**Comment by KillerInk** [comment]
let it run now for 8 hours. no shares found 😢 
the first 10 shares have a difficult 10000. on cuda based miner it get returned after a few seconds
but could be that i messed up the aes part

i tested different worksizes: fastes hashes gets produced with 8.
i also test your suggestion with 11x8x16. it drops hashes from 300 to 127.
8x32x8 = 327h/s
8x32x16 = 300h/s
8x32x32 = 270h/s

think its best to wait till you push a new release build with gcc^^

**Comment by KillerInk** [comment]
@G-Kumaran 
i found the solution for our mingw problem
 **x86_64-w64-mingw32-g++-win32**
need replaced with:
**x86_64-w64-mingw32-g++**

files to edit:
build\CMakeFiles\miner.dir\link.txt
build\CMakeFiles\miner.dir\build.make

happy building

**Comment by G-Kumaran** [comment]
Thx! I think it'll wait for the offical repo release. 
Currently on turtle, but srb is way over powered so will postpone testing
