### ISSUE TITLE
Console refresh rate ?? wont continue with any value.

### ISSUE THREAD

**Issue by rafise** [enerc/VulkanXMRMiner#8]
Trying to set the refresh can some tell me if I'm doing something wrong thanks.
already tried 30s , 5s, 30, 5 also hitting enter for default nothing work.

Console refresh rate (default 30s): 35
Failure in vkCreateInstance at 69 /home/rafi/VulkanXMRMiner/src/mvulkan.cpp  ErrCode=-9

**Comment by rafise** [comment]
Guys Already found the issue, was running the miner under my user, need to be run with sudo.

**Comment by 949f45ac** [comment]
If it doesn’t run without sudo, you might need to add your user to the video group.
`sudo usermod -a -G video $LOGNAME`
Cheers.

**Comment by enerc** [comment]
As 949f45ac pointed out, it's much better to add yourself to the video group than running it as root.
For the graphic console, set port above 1024 (as port below 1024 requires root on Linux).
